using System.Text.Json.Serialization;

namespace MMM_Server.Models
{
    public enum RealCurrencies
    {
        [JsonPropertyName("AED")] Aed,
        [JsonPropertyName("AFN")] Afn,
        [JsonPropertyName("ALL")] All,
        [JsonPropertyName("AMD")] Amd,
        [JsonPropertyName("ANG")] Ang,
        [JsonPropertyName("AOA")] Aoa,
        [JsonPropertyName("ARS")] Ars,
        [JsonPropertyName("AUD")] Aud,
        [JsonPropertyName("AWG")] Awg,
        [JsonPropertyName("AZN")] Azn,

        [JsonPropertyName("BAM")] Bam,
        [JsonPropertyName("BBD")] Bbd,
        [JsonPropertyName("BDT")] Bdt,
        [JsonPropertyName("BGN")] Bgn,
        [JsonPropertyName("BHD")] Bhd,
        [JsonPropertyName("BIF")] Bif,
        [JsonPropertyName("BMD")] Bmd,
        [JsonPropertyName("BND")] Bnd,
        [JsonPropertyName("BOB")] Bob,
        [JsonPropertyName("BOV")] Bov,
        [JsonPropertyName("BRL")] Brl,
        [JsonPropertyName("BSD")] Bsd,
        [JsonPropertyName("BTN")] Btn,
        [JsonPropertyName("BWP")] Bwp,
        [JsonPropertyName("BYN")] Byn,
        [JsonPropertyName("BZD")] Bzd,

        [JsonPropertyName("CAD")] Cad,
        [JsonPropertyName("CDF")] Cdf,
        [JsonPropertyName("CHE")] Che,
        [JsonPropertyName("CHF")] Chf,
        [JsonPropertyName("CHW")] Chw,
        [JsonPropertyName("CLF")] Clf,
        [JsonPropertyName("CLP")] Clp,
        [JsonPropertyName("CNY")] Cny,
        [JsonPropertyName("COP")] Cop,
        [JsonPropertyName("COU")] Cou,
        [JsonPropertyName("CRC")] Crc,
        [JsonPropertyName("CUP")] Cup,
        [JsonPropertyName("CVE")] Cve,
        [JsonPropertyName("CZK")] Czk,

        [JsonPropertyName("DJF")] Djf,
        [JsonPropertyName("DKK")] Dkk,
        [JsonPropertyName("DOP")] Dop,
        [JsonPropertyName("DZD")] Dzd,

        [JsonPropertyName("EGP")] Egp,
        [JsonPropertyName("ERN")] Ern,
        [JsonPropertyName("ETB")] Etb,
        [JsonPropertyName("EUR")] Eur,

        [JsonPropertyName("FJD")] Fjd,
        [JsonPropertyName("FKP")] Fkp,

        [JsonPropertyName("GBP")] Gbp,
        [JsonPropertyName("GEL")] Gel,
        [JsonPropertyName("GHS")] Ghs,
        [JsonPropertyName("GIP")] Gip,
        [JsonPropertyName("GMD")] Gmd,
        [JsonPropertyName("GNF")] Gnf,
        [JsonPropertyName("GTQ")] Gtq,
        [JsonPropertyName("GYD")] Gyd,

        [JsonPropertyName("HKD")] Hkd,
        [JsonPropertyName("HNL")] Hnl,
        [JsonPropertyName("HTG")] Htg,
        [JsonPropertyName("HUF")] Huf,

        [JsonPropertyName("IDR")] Idr,
        [JsonPropertyName("ILS")] Ils,
        [JsonPropertyName("INR")] Inr,
        [JsonPropertyName("IQD")] Iqd,
        [JsonPropertyName("IRR")] Irr,
        [JsonPropertyName("ISK")] Isk,

        [JsonPropertyName("JMD")] Jmd,
        [JsonPropertyName("JOD")] Jod,
        [JsonPropertyName("JPY")] Jpy,

        [JsonPropertyName("KES")] Kes,
        [JsonPropertyName("KGS")] Kgs,
        [JsonPropertyName("KHR")] Khr,
        [JsonPropertyName("KMF")] Kmf,
        [JsonPropertyName("KPW")] Kpw,
        [JsonPropertyName("KRW")] Krw,
        [JsonPropertyName("KWD")] Kwd,
        [JsonPropertyName("KYD")] Kyd,
        [JsonPropertyName("KZT")] Kzt,

        [JsonPropertyName("LAK")] Lak,
        [JsonPropertyName("LBP")] Lbp,
        [JsonPropertyName("LKR")] Lkr,
        [JsonPropertyName("LRD")] Lrd,
        [JsonPropertyName("LSL")] Lsl,
        [JsonPropertyName("LYD")] Lyd,

        [JsonPropertyName("MAD")] Mad,
        [JsonPropertyName("MDL")] Mdl,
        [JsonPropertyName("MGA")] Mga,
        [JsonPropertyName("MKD")] Mkd,
        [JsonPropertyName("MMK")] Mmk,
        [JsonPropertyName("MNT")] Mnt,
        [JsonPropertyName("MOP")] Mop,
        [JsonPropertyName("MRU")] Mru,
        [JsonPropertyName("MUR")] Mur,
        [JsonPropertyName("MVR")] Mvr,
        [JsonPropertyName("MWK")] Mwk,
        [JsonPropertyName("MXN")] Mxn,
        [JsonPropertyName("MXV")] Mxv,
        [JsonPropertyName("MYR")] Myr,
        [JsonPropertyName("MZN")] Mzn,

        [JsonPropertyName("NAD")] Nad,
        [JsonPropertyName("NGN")] Ngn,
        [JsonPropertyName("NIO")] Nio,
        [JsonPropertyName("NOK")] Nok,
        [JsonPropertyName("NPR")] Npr,
        [JsonPropertyName("NZD")] Nzd,

        [JsonPropertyName("OMR")] Omr,

        [JsonPropertyName("PAB")] Pab,
        [JsonPropertyName("PEN")] Pen,
        [JsonPropertyName("PGK")] Pgk,
        [JsonPropertyName("PHP")] Php,
        [JsonPropertyName("PKR")] Pkr,
        [JsonPropertyName("PLN")] Pln,
        [JsonPropertyName("PYG")] Pyg,

        [JsonPropertyName("QAR")] Qar,

        [JsonPropertyName("RON")] Ron,
        [JsonPropertyName("RSD")] Rsd,
        [JsonPropertyName("RUB")] Rub,
        [JsonPropertyName("RWF")] Rwf,

        [JsonPropertyName("SAR")] Sar,
        [JsonPropertyName("SBD")] Sbd,
        [JsonPropertyName("SCR")] Scr,
        [JsonPropertyName("SDG")] Sdg,
        [JsonPropertyName("SEK")] Sek,
        [JsonPropertyName("SGD")] Sgd,
        [JsonPropertyName("SHP")] Shp,
        [JsonPropertyName("SLE")] Sle,
        [JsonPropertyName("SOS")] Sos,
        [JsonPropertyName("SRD")] Srd,
        [JsonPropertyName("SSP")] Ssp,
        [JsonPropertyName("STN")] Stn,
        [JsonPropertyName("SVC")] Svc,
        [JsonPropertyName("SYP")] Syp,
        [JsonPropertyName("SZL")] Szl,

        [JsonPropertyName("THB")] Thb,
        [JsonPropertyName("TJS")] Tjs,
        [JsonPropertyName("TMT")] Tmt,
        [JsonPropertyName("TND")] Tnd,
        [JsonPropertyName("TOP")] Top,
        [JsonPropertyName("TRY")] Try,
        [JsonPropertyName("TTD")] Ttd,
        [JsonPropertyName("TWD")] Twd,
        [JsonPropertyName("TZS")] Tzs,

        [JsonPropertyName("UAH")] Uah,
        [JsonPropertyName("UGX")] Ugx,
        [JsonPropertyName("USD")] Usd,
        [JsonPropertyName("USN")] Usn,
        [JsonPropertyName("UYI")] Uyi,
        [JsonPropertyName("UYU")] Uyu,
        [JsonPropertyName("UYW")] Uyw,
        [JsonPropertyName("UZS")] Uzs,

        [JsonPropertyName("VED")] Ved,
        [JsonPropertyName("VES")] Ves,
        [JsonPropertyName("VND")] Vnd,
        [JsonPropertyName("VUV")] Vuv,

        [JsonPropertyName("WST")] Wst,

        [JsonPropertyName("XAF")] Xaf,
        [JsonPropertyName("XAG")] Xag,
        [JsonPropertyName("XAU")] Xau,
        [JsonPropertyName("XBA")] Xba,
        [JsonPropertyName("XBB")] Xbb,
        [JsonPropertyName("XBC")] Xbc,
        [JsonPropertyName("XBD")] Xbd,
        [JsonPropertyName("XCD")] Xcd,
        [JsonPropertyName("XDR")] Xdr,
        [JsonPropertyName("XOF")] Xof,
        [JsonPropertyName("XPD")] Xpd,
        [JsonPropertyName("XPF")] Xpf,
        [JsonPropertyName("XPT")] Xpt,
        [JsonPropertyName("XSU")] Xsu,
        [JsonPropertyName("XTS")] Xts,
        [JsonPropertyName("XUA")] Xua,
        [JsonPropertyName("XXX")] Xxx,

        [JsonPropertyName("YER")] Yer,

        [JsonPropertyName("ZAR")] Zar,
        [JsonPropertyName("ZMW")] Zmw,
        [JsonPropertyName("ZWG")] Zwg
    }
}
